spring:
  application:
    name: questionsrepository
  cache:
    cache-names: questions
    caffeine:
      spec: maximumSize=500,expireAfterAccess=1200s
    type: caffeine
    multi:
      caffeine:
        expireAfterAccess: 300000
      redis:
        defaultExpiration: 600000
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      uri: mongodb://localhost:27017/school

server:
  port: 8088
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    #ip-address: 114.115.207.28
    #prefer-ip-address: true

# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

com:
  jichuangsi:
    school:
      result:
        page-size: 10
      token:
          userClaim : userInfo
      tiku:
        schema: http
        host: 127.0.0.1
        port: 80
        accessKey: 9229eb41327ec6385c28baf45469f988
        subjectEditionApi: subjectEditionApi
        otherBasicApi: getOtherBasic
        chapterApi: chapterApi
        questionApi: getQuestions
        answerApi: getAnswer
        knowledgeApi: knowledgeApi
      swagger:
        enable: true
      codePic:
        time: 300000
        prefix: pic_