spring:
  application:
    name: questionsrepository
server:
  port: 8085
    
eureka: 
  client:    
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/ #http://114.115.207.28:8081/eureka/
  #instance:
    #ip-address: 114.115.207.28
    #prefer-ip-address: true

com:
  jichuangsi:
    school:
      token:
          userClaim : userInfo