spring:
  application:
    name: parentservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/school
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  devtools:
    freemarker:
      cache:false
server:
  port: 7979


eureka: 
  client:    
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  #instance:
    #ip-address: 114.115.207.28
    #prefer-ip-address: true

com:
  jichuangsi:
    school:
      token:
          jwt:
            secret: EC86@34$123c
            userClaim : userInfo
      swagger:
        enable: true
